### ISSUE TITLE
Is the corresponding ROS package open source?

### ISSUE THREAD

**Issue by wuhanstudio** [1487quantum/ros-pibot#1]
Hello, I'm a master student from China working on mobile robot powered by ROS.

This project is a really good starting point for me. Thanks a lot for your help. But I failed to find the corresponding source code on ROS side, is it available on github?

Thanks again for your help.

**Comment by quantumxt** [comment]
Hi, there is a tutorial on configuring the Arduino to work with ROS, you can check it out over here: https://wiki.ros.org/rosserial_arduino/Tutorials

**Comment by wuhanstudio** [comment]
> Hi, there is a tutorial on configuring the Arduino to work with ROS, you can check it out over here: https://wiki.ros.org/rosserial_arduino/Tutorials

Thanks for your help. I've managed to control the robot using rospy.
